# Generated by Django 3.2.13 on 2022-04-23 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
