#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/api/manage.py collectstatic --noinput
python /app/api/manage.py migrate

/usr/local/bin/gunicorn core.asgi --bind 0.0.0.0:80 --chdir=/app
