# Generated by Django 3.2.23 on 2023-12-10 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20200402_0908'),
        ('cart', '0006_auto_20200529_1313'),
    ]

    operations = [
    ]
